import os
import time
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
import mlflow
import numpy as np

# Initialize FastAPI application
app = FastAPI(
    title="AuraPM Predictive Analytics Engine",
    version="1.0.0",
    description="MLOps microservice for predicting enterprise delivery and sprint spillover risks."
)

# Configure Local MLflow Storage Directory
MLFLOW_TRACKING_DIR = os.getenv("MLFLOW_TRACKING_URI", "./mlruns")
mlflow.set_tracking_uri(f"file://{os.path.abspath(MLFLOW_TRACKING_DIR)}")
mlflow.set_experiment("Sprint_Velocity_Forecasting")

# Data Transfer Object (DTO) Input Contract using Pydantic
class IssueMetricsDTO(BaseModel):
    issue_id: str = Field(..., description="The unique UUID of the ticket generated by Java.")
    story_points: int = Field(..., ge=0, description="The estimated engineering complexity score.")
    description_length: int = Field(..., ge=0, description="Length of the text instructions.")
    historical_spillover_rate: float = Field(..., ge=0.0, le=1.0, description="Team failure tracking rate.")

# Output DTO Response Contract
class PredictionResponseDTO(BaseModel):
    issue_id: str
    spillover_probability: float
    risk_level: str
    processing_time_ms: float

@app.post("/api/v1/analytics/predict-spillover", response_model=PredictionResponseDTO)
async def predict_spillover(metrics: IssueMetricsDTO):
    start_time = time.time()
    
    try:
        # Start an isolated MLOps Telemetry Transaction Run
        with mlflow.start_run(run_name=f"api_prediction_{metrics.issue_id[:8]}"):
            
            # Log structural parameters directly to the local MLflow dashboard
            mlflow.log_param("issue_id", metrics.issue_id)
            mlflow.log_param("story_points", metrics.story_points)
            mlflow.log_param("description_length", metrics.description_length)
            
            # Statistical Risk Formula (Simulating a Production Logistic Model)
            # Higher points + low documentation + bad history = exponential risk spike
            linear_combination = (
                (metrics.story_points * 0.35) - 
                (metrics.description_length * 0.002) + 
                (metrics.historical_spillover_rate * 2.5) - 1.5
            )
            
            # Sigmoid activation to squash values into a clean 0 to 1 probability range
            spillover_probability = 1.0 / (1.0 + np.exp(-linear_combination))
            spillover_probability = float(np.round(spillover_probability, 4))
            
            # Classify operational danger thresholds
            if spillover_probability < 0.40:
                risk_level = "LOW"
            elif spillover_probability < 0.75:
                risk_level = "MEDIUM"
            else:
                risk_level = "HIGH"
                
            processing_time = (time.time() - start_time) * 1000
            
            # Log downstream metrics back to MLflow tracking engine
            mlflow.log_metric("spillover_probability", spillover_probability)
            mlflow.log_metric("processing_time_ms", processing_time)
            
            # Tag the transaction for system audit logging
            mlflow.set_tag("environment", "local_development")
            mlflow.set_tag("engine", "fastapi_async")

            return PredictionResponseDTO(
                issue_id=metrics.issue_id,
                spillover_probability=spillover_probability,
                risk_level=risk_level,
                processing_time_ms=np.round(processing_time, 2)
            )
            
    except Exception as e:
        mlflow.log_param("status", "FAILED")
        raise HTTPException(status_code=500, detail=f"MLOps Evaluation Interrupted: {str(e)}")